name: Learning GitHub Script

on:
  issues:
    types: [opened]
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: contextx.repo.owner,
              repo: context.repo.repo,
              body: ":video_game: You've created this issue usingg Github Script!! :snowflake:"
            })
