name: Learning GitHub Script

on:
  issues:
    types: [opened]
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: ":video_game: You've created this issue using Github Script!! :snowflake:"
            })

      - name: Add issue to project board
        if: contains(github.event.issue.labels.*.name, 'bug')
        uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
              github.projects.createCard({
              column_id: 18949536,
              content_id: context.payload.issue.id,
              content_type: "Issue"
              });
